
import type { Order } from '@/hooks/use-orders';

// This is now exported so it can be modified by hooks, simulating a database.
export let initialOrders: Order[] = [
    {
      id: "ord-1",
      display_id: "BEM-ABC123",
      created_at: "2024-05-20T10:00:00Z",
      user_id: "user-1-admin",
      customer_id: "cust-1",
      customer_name: "Elena Rodríguez",
      customer_phone: "9988-7766",
      customer_address: {
        department: "Francisco Morazán",
        municipality: "Distrito Central",
        colony: "Col. Palmira",
        exactAddress: "Frente a la embajada, casa 123",
      },
      items: [
        { id: "prod_1", name: "Suero Facial Hidratante con Ácido Hialurónico", price: 650, quantity: 1, image: 'https://placehold.co/400x400.png' },
        { id: "prod_6", name: "Paleta de Sombras 'Atardecer Dorado'", price: 950, quantity: 1, image: 'https://placehold.co/400x400.png' },
      ],
      total: 1600,
      shipping_cost: 0,
      balance: 0,
      payments: [{ amount: 1600, date: "2024-05-20T10:05:00Z", method: 'tarjeta' }],
      payment_method: 'tarjeta',
      payment_reference: 'ref-12345',
      status: 'paid',
      source: 'pos',
      delivery_method: 'pickup',
      payment_due_date: null,
    },
    {
      id: "ord-2",
      display_id: "BEM-DEF456",
      created_at: "2024-05-21T14:30:00Z",
      user_id: null,
      customer_id: "cust-2",
      customer_name: "Carlos Portillo",
      customer_phone: "3322-1100",
      customer_address: {
        department: "Cortés",
        municipality: "San Pedro Sula",
        colony: "Col. Universitaria",
        exactAddress: "Calle principal, casa 45",
      },
      items: [
        { id: "prod_2", name: "Base de Maquillaje Cobertura Total Mate", price: 850, quantity: 1, image: 'https://placehold.co/400x400.png' },
      ],
      total: 1000,
      shipping_cost: 150,
      balance: 1000,
      payments: [],
      payment_method: 'efectivo',
      payment_reference: null,
      status: 'pending-approval',
      source: 'online-store',
      delivery_method: 'delivery',
      payment_due_date: null,
    },
    {
      id: "ord-3",
      display_id: "BEM-GHI789",
      created_at: "2024-05-22T09:00:00Z",
      user_id: "user-2-cajero",
      customer_id: null,
      customer_name: "Consumidor Final",
      customer_phone: "N/A",
      customer_address: null,
      items: [
        { id: "prod_7", name: "Mascarilla Capilar Intensiva de Keratina", price: 680, quantity: 2, image: 'https://placehold.co/400x400.png' },
      ],
      total: 1360,
      shipping_cost: 0,
      balance: 1360,
      payments: [],
      payment_method: 'credito',
      payment_reference: null,
      status: 'pending-payment',
      source: 'pos',
      delivery_method: 'pickup',
      payment_due_date: "2024-06-22T09:00:00Z",
    },
];
